version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "5001:5001"
    env_file:
      - ../.env
    depends_on:
      - postgres

  postgres:
    image: 'postgres:13.2-alpine'
    volumes:
      - 'Delta-postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    env_file:
      - ../.env

volumes:
  Delta-postgres:
